#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  pkg ensure editors/vim
  ln -nfs vim "$PKG_HOME/install/bin/vi"

  git submodule update --init
  git submodule foreach git reset --hard

  local tmp_scratch="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_scratch")" EXIT
  vim -e -c ":source $tmp_scratch" -c :quit meh || true
  vim -e -c ":source $tmp_scratch" -c :quit meh || true
}

bootstrap
