#!/usr/bin/env bash

function junas_fresh {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -x "${PKG_HOME}/install/bin/vim" ]]; then
    return 1
  fi

  local cnt_changed="$(git status -s --ignore-submodules=untracked | grep -v '^??')"

  if [[ -n "$cnt_changed" ]]; then
    return 1
  fi

  return 0
}

junas_fresh
