#!/bin/bash

function vi {
  _junas_cmd_vi=$(type -P vim || type -P mvim || true)

  local pth_xc="$(type -P xtermset || true)"

  local old_bg=
  if [[ -x "$pth_xc" ]]; then
    if [[ -n "${CUE_BG:-}" ]]; then
      $pth_xc -bg rgb:1c1c/1c1c/1c1c
    fi
  fi

  $_junas_cmd_vi -X "$@"

  if [[ -x "$pth_xc" && -n "${CUE_BG:-}" ]]; then
    $pth_xc -bg "$CUE_BG"
  fi
}


if [[ -x $_junas_cmd_vi ]]; then
  export EDITOR="$_junas_cmd_vi"
fi
